export const QUERY_KEYS = {
  currentListing: "currentListing",
  courtOptions: "courtOptions",
  titleOptions: "titleOptions",
  personOptions: "personOptions",
  defaults: "defaults",
  listingsPath: "listingsPath",
  recents: "recentListings",
  createListing: "createListing",
  listings: "listings",
  court: "getCourt",
  courts: "courts",
  summons: "summons",
  summonStatus: "summonStatus",
} as const;
